server.port=8090

spring.data.mongodb.username=username
spring.data.mongodb.password=password
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=customer
spring.data.mongodb.authentication-database=admin

spring.zipkin.base-url=http://localhost:9422

# Keycloak Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/ecart-realm

management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true