# Eureka server configuration
spring.application.name=discovery-service
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Eureka client configuration (disabling registration and fetching registry)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Server configuration
server.port=8761

management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true


