spring.datasource.url=jdbc:postgresql://postgresql:5432/payment
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.bootstrap-servers=kafka:9092
application.config.product-url=http://gateway:8222/api/v1/products
eureka.client.service-url.defaultZone=http://discovery:8761/eureka