spring.application.name=customer-service
spring.config.import=optional:configserver:http://localhost:8888

#management.zipkin.tracing.endpoint=
server.port=8090
spring.data.mongodb.username=swapnil
spring.data.mongodb.password=swapnil
spring.data.host=localhost
spring.data.port=27017
spring.data.database=customer
spring.data.authentication-database=admin
#eureka.client.service-url.defaultZone=http://3.110.45.200:8761/eureka
#spring.zipkin.base-url=http://3.110.45.200:9411
